{% set name = "genai" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/genai-{{ version }}.tar.gz
  sha256: 71abe894703d2a097148fd08152bedd3f320598536317dc0cd9bee69e9f87314

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0.1
  run:
    - python >=3.8
    - openai >=0.27.0
    - vdom >=0.6
    - ipython >=8.10.0
    - tabulate >=0.9.0
    - tiktoken >=0.3.2


test:
  imports:
    - genai
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Generative AI for IPython (enhance your code cells)
  description: |
    Generative AI tooling for IPython using OpenAI's API.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/noteable-io/genai
  doc_url: https://github.com/noteable-io/genai
  dev_url: https://github.com/noteable-io/genai



extra:
  recipe-maintainers:
    - andersy005
