{% set name = "genai" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/genai-{{ version }}.tar.gz
  sha256: 66e817753528be10ecff33f682cda4545f831c2f74d36b0f5273e754fb56f197

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0.1
  run:
    - python >=3.8
    - openai >=0.27.0
    - vdom >=0.6
    - ipython >=8.10.0

test:
  imports:
    - genai
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Generative AI for IPython (enhance your code cells)
  description: |
    Generative AI tooling for IPython using OpenAI's API.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/noteable-io/genai
  doc_url: https://github.com/noteable-io/genai
  dev_url: https://github.com/noteable-io/genai



extra:
  recipe-maintainers:
    - andersy005
